### PR TITLE
Go.uuid instead of own version

### PR DESCRIPTION
**Pull request by cyx**
Throwing out there if it makes sense

### CODE REVIEW

**Comment by tt** [comment]
I'm not a huge fan of that library (or any of the libraries; I have my own which I never released because I thought it was silly with a ton of very basic UUID libraries). It doesn't consider that reading might fail, so you could get an empty UUID.

**Comment by cyx** [comment]
Yep, makes sense.

**Comment by catsby** [comment]
revisiting: what about https://code.google.com/p/go-uuid ?

**Comment by cyx** [comment]
Yeah based on some googling some people complain it's not RFC compliant --
but if we don't care about
that I'm fine using that.

**Pull request closed without merging**
