### PR TITLE
rename the busltee package to publisher

### PR DESCRIPTION
**Pull request by dmathieu**
Having a command and package named busl can be quite misleading as to  where something should be.
This rename makes it clearer this package is the lower-level interface allowing publishing data.

### CODE REVIEW

**Comment by tt** [comment]
I think that's actually a Go pattern; that the `cmd/...` package should only contain very little logic and delegate to a package.

The package is not a generic publisher. It's limited to the `tee` like operation required by the command.

**Comment by dmathieu** [comment]
My point here is mostly that the term `busltee` doesn't have any obvious meaning, and it can be hard to guess what this package does at first.
Even though this is not a generic publisher, I believe renaming this package makes it clearer on what it does.

**Comment by dmathieu** [comment]
@tt is there a name you'd better agree with?

**Comment by dmathieu** [comment]
Let's punt on this for now.

**Pull request closed without merging**
