### PR TITLE
Re-add busltee

### PR DESCRIPTION
**Pull request by cyx**

### CODE REVIEW

**Comment by ojacobson** [comment]
:+1:

**Comment by freeformz** [comment]
ship it ?

**Comment by cyx** [comment]
Just to note, busltee needs to be compiled against Go master. @freeformz
does this already for most of his stuff but wanted to highlight that.

(Otherwise streams won't be streams, and will be 4096 chunks of data
written out)

**Comment by freeformz** [comment]
@cyx We can likely just use 1.5beta1?

**Comment by freeformz** [comment]
FWIW: which is what I run now locally

**Comment by cyx** [comment]
Yes for sure 1.5beta1 works

**Pull request merged**
